### ISSUE TITLE
Support for vehicle trailers

### ISSUE THREAD

**Issue by glitchdetector** [justalemon/SimplePassive#3]
Looking at the source, there's no support for vehicles with trailers attached.
Would it be possible to also prevent collisions for attached trailers?

**Comment by justalemon** [comment]
I forgot that trailers and hooked vehicles do not inherit the properties of the parent vehicle.

**Comment by justalemon** [comment]
I just pushed 9c8538d5a4579e4463e22228cb86d932d5535f23 that should support trailers and vehicles hooked by cargobobs and towtrucks. I have not tested it yet, but if you have the time you can download the build from https://ci.appveyor.com/project/justalemon/simplepassive/builds/33168473/artifacts and see if it works.

**Comment by glitchdetector** [comment]
Thank you, I will run some tests and come back with the results.

**Comment by glitchdetector** [comment]
So, from a bit of testing (using a semi-cab and a trailer):

While a semi-cab has a trailer attached:
The driver of the semi-cab will still see the semi-cab hitting player's vehicles, while the trailer itself works as intended. Other players simply pass right through the semi-cab and trailer.
Detaching the trailer has the semi-cab working as normal again.

Simply, the semi-cab appears to not have proper no-collision for the driver of the semi-cab while a trailer is attached.

The same is true for the Cargobob hook and the Towtruck (Cargobob is solid on the drivers screen while something is attached, Towtruck is solid on the drivers screen while something is attached)

Hopefully those can be fixed <3

**Comment by justalemon** [comment]
So, when you hook onto something the main vehicle that you are using becomes solid.

Did I get this right?

**Comment by glitchdetector** [comment]
> So, when you hook onto something the main vehicle that you are using becomes solid.

Correct, but only for _yourself_.
Other players have zero collision with your main vehicle or the attached one.

**Comment by justalemon** [comment]
https://github.com/justalemon/SimplePassive/blob/9c8538d5a4579e4463e22228cb86d932d5535f23/SimplePassive.Client/Passive.cs#L152-L153

https://github.com/justalemon/SimplePassive/blob/9c8538d5a4579e4463e22228cb86d932d5535f23/SimplePassive.Client/Extensions.cs#L63-L65

Hmm...

**Comment by justalemon** [comment]
I changed a bit the way collisions are changed in 4b13d4cd21d1e5fe476fb4e0f94da76e2421607f. The automated build can be found in https://ci.appveyor.com/project/justalemon/simplepassive/builds/33185435/artifacts.

I can't test it because I don't have anyone to test it with right now and I can't run 2 FiveM copies at the same time.

**Comment by justalemon** [comment]
I managed to test it with someone and appears to be fully working.

@glitchdetector if you find any problems, let me know.

**Comment by glitchdetector** [comment]
Thank you!

**Comment by glitchdetector** [comment]
I still experience the issue, the build should be updated as the changes for #17 are present
Here's a video of the issue, the same occurs in all 3 combinations of enabled passive mode.
https://youtu.be/ZN5jUqVPpTE (both players have passive mode enabled in the video)

**Comment by justalemon** [comment]
> the build should be updated as the changes for #17 are present

You want an up to date build with the changes on #17? You can always download the latest development build from https://ci.appveyor.com/project/justalemon/simplepassive/build/artifacts

**Comment by justalemon** [comment]
I tried again and it works on my side (you can see that there is a trailer hooked behind).

![image](https://user-images.githubusercontent.com/11861253/83316808-2996d900-a1f6-11ea-9570-5a4a3bd73c69.png)

**Comment by glitchdetector** [comment]
Would you be able to upload an updated release of the built resource then?
Not sure how the AppVeyor building works, but given that the most recent artifact there has the fixes introduced in #17 (which were part of a more recent commit), I'd assume that the fixes in this issue are also in that build.
The video was recorded while using the 0.1.0.88 build on AppVeyor, which is the most recent available.

**Comment by justalemon** [comment]
I'm actually using 0.1.0.88, but built locally (that should theoretically not change anything).

**Comment by justalemon** [comment]
I forgot to check my FiveM projects.

I remember that we talked about this in Discord where the it didn't worked on the server where it was being tested but it worked perfectly in a clean FiveM Server.

Because of this, I will be closing this issue as implemented.
